
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 12 18:57:48 CEST 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 44;
  public static final int LBRACKET = 19;
  public static final int GREATER_OR_EQUAL = 37;
  public static final int CONST = 16;
  public static final int NOT_EQUAL = 41;
  public static final int GREATER = 36;
  public static final int LPAREN = 17;
  public static final int SEMI = 23;
  public static final int CONTINUE = 15;
  public static final int NUM_CONST = 43;
  public static final int LESS = 38;
  public static final int MINUS = 28;
  public static final int RPAREN = 18;
  public static final int LESS_OR_EQUAL = 39;
  public static final int COMMA = 24;
  public static final int CLASS = 4;
  public static final int INC = 34;
  public static final int DIV = 30;
  public static final int PLUS = 27;
  public static final int IF = 5;
  public static final int IS_EQUAL = 40;
  public static final int DOT = 25;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RBRACKET = 20;
  public static final int EQUAL = 26;
  public static final int LOGICAL_OR = 33;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int MUL = 29;
  public static final int MOD = 31;
  public static final int IDENT = 42;
  public static final int BREAK = 3;
  public static final int VOID = 11;
  public static final int LBRACE = 21;
  public static final int ELSE = 6;
  public static final int READ = 9;
  public static final int WHILE = 13;
  public static final int LOGICAL_AND = 32;
  public static final int RBRACE = 22;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 45;
  public static final int DEC = 35;
  public static final int PRINT = 8;
  public static final int DO = 12;
}

